name: Build
on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  sonarqube:
    name: SonarQube
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Recommended for SonarQube

      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@v5
        with:
          args: >
            -Dsonar.projectKey=Rajesh-cloudangles_oneclick-Bk
            -Dsonar.organization=rajesh-cloudangles
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
